<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HousingManagementSystem.API\HousingManagementSystem.API.csproj" />
    <ProjectReference Include="..\HousingManagementSystem.Application\HousingManagementSystem.Application.csproj" />
    <ProjectReference Include="..\HousingManagementSystem.Domain\HousingManagementSystem.Domain.csproj" />
    <ProjectReference Include="..\HousingManagementSystem.Infrastructure\HousingManagementSystem.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>